<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ProductOptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
     //    DB::table('product_options')->insert([
     //        'id' => 1,
     //        'name' => 'Colors',
     //        'type' => 'option',
     //        'hide_on' => '""',
     //        'order' => '1',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 2,
     //        'name' => 'Finishes',
     //        'type' => 'finishes',
     //        'hide_on' => '""',
     //        'order' => '2',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 3,
     //        'name' => 'MultiSelect',
     //        'type' => 'multi',
     //        'hide_on' => '""',
     //        'order' => '3',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 4,
     //        'name' => 'Extras and price',
     //        'type' => 'text',
     //        'hide_on' => '""',
     //        'order' => '4',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 5,
     //        'name' => 'TEXT ONLY',
     //        'type' => 'text_only',
     //        'hide_on' => '""',
     //        'order' => '5',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 6,
     //        'name' => 'Display ONLY',
     //        'type' => 'display',
     //        'hide_on' => '""',
     //        'order' => '6',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 7,
     //        'name' => 'Price oNLY',
     //        'type' => 'price',
     //        'hide_on' => '""',
     //        'order' => '7',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 8,
     //        'name' => 'Cost Priceeee',
     //        'type' => 'cost_price',
     //        'hide_on' => '""',
     //        'order' => '8',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 9,
     //        'name' => 'Manuuuuu',
     //        'type' => 'manufactOring',
     //        'hide_on' => '""',
     //        'order' => '9',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 10,
     //        'name' => 'Fabric Qnty',
     //        'type' => 'fabric_quantity',
     //        'hide_on' => '""',
     //        'order' => '10',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 11,
     //        'name' => 'Fabric Qnt Not Edit',
     //        'type' => 'fabric_quantity_not_edit',
     //        'hide_on' => '""',
     //        'order' => '11',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 12,
     //        'name' => 'All Fab',
     //        'type' => 'fabric',
     //        'hide_on' => '""',
     //        'order' => '12',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 13,
     //        'name' => 'Trim lang kuya',
     //        'type' => 'trim',
     //        'hide_on' => '""',
     //        'order' => '13',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 14,
     //        'name' => 'Silver Lining',
     //        'type' => 'lining',
     //        'hide_on' => '""',
     //        'order' => '14',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 15,
     //        'name' => 'Accessorry Na',
     //        'type' => 'accessory',
     //        'hide_on' => '""',
     //        'order' => '15',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 16,
     //        'name' => 'GRUPO NG MGA GWAPO',
     //        'type' => 'group',
     //        'hide_on' => '""',
     //        'order' => '16',
     //        'product_option_id' => '0',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 17,
     //        'name' => 'ELEMENTS',
     //        'type' => 'option',
     //        'hide_on' => '""',
     //        'order' => '17',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 18,
     //        'name' => 'FINISHER',
     //        'type' => 'finishes',
     //        'hide_on' => '""',
     //        'order' => '18',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 19,
     //        'name' => 'CRUSHES',
     //        'type' => 'multi',
     //        'hide_on' => '""',
     //        'order' => '19',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 20,
     //        'name' => 'Extras and price G',
     //        'type' => 'text',
     //        'hide_on' => '""',
     //        'order' => '20',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 21,
     //        'name' => 'TEXT ONLY SIR G',
     //        'type' => 'text_only',
     //        'hide_on' => '""',
     //        'order' => '21',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 22,
     //        'name' => 'Display Lang G',
     //        'type' => 'display',
     //        'hide_on' => '""',
     //        'order' => '22',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 23,
     //        'name' => 'Price G',
     //        'type' => 'price',
     //        'hide_on' => '""',
     //        'order' => '23',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 24,
     //        'name' => 'Cost Priceeee GGGG',
     //        'type' => 'cost_price',
     //        'hide_on' => '""',
     //        'order' => '24',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 25,
     //        'name' => 'ManuuuuunG',
     //        'type' => 'manufacturing',
     //        'hide_on' => '""',
     //        'order' => '25',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 26,
     //        'name' => 'Fabric Qnty G',
     //        'type' => 'fabric_quantity',
     //        'hide_on' => '""',
     //        'order' => '26',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 27,
     //        'name' => 'Fabric Qnt Not Edit G',
     //        'type' => 'fabric_quantity_not_edit',
     //        'hide_on' => '""',
     //        'order' => '27',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 28,
     //        'name' => 'All Fab g',
     //        'type' => 'fabric',
     //        'hide_on' => '""',
     //        'order' => '28',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 29,
     //        'name' => 'Trim lang kuya G',
     //        'type' => 'trim',
     //        'hide_on' => '""',
     //        'order' => '29',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 30,
     //        'name' => 'Silver LiningGGGrrr',
     //        'type' => 'lining',
     //        'hide_on' => '""',
     //        'order' => '30',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_options')->insert([
     //        'id' => 31,
     //        'name' => 'Accessorry Na g',
     //        'type' => 'accessory',
     //        'hide_on' => '""',
     //        'order' => '31',
     //        'product_option_id' => '16',
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);

     //    DB::table('product_options')->insert([
     //        'id' => 32,
     //        'name' => 'Option With sub yea',
     //        'type' => 'option',
     //        'hide_on' => '""',
     //        'order' => '32',
     //        'product_option_id' => 0,
     //        'product_id' => '1',
     //        'constraint_id' => '0',
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);

     //    /*
     //    Selects 
     //     */
        
     //    DB::table('product_option_selects')->insert([
     //        'id' => 1,
     //        'name' => 'Red',
     //        'order' => 1,
     //        'value' => 5,
     //        'product_option_id' => 1,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 2,
     //        'name' => 'Blue',
     //        'order' => 2,
     //        'value' => 10,
     //        'product_option_id' => 1,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 3,
     //        'name' => 'Green',
     //        'order' => 3,
     //        'value' => 8,
     //        'product_option_id' => 1,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);

     //    DB::table('product_option_selects')->insert([
     //        'id' => 4,
     //        'name' => 'Finland 1',
     //        'order' => 4,
     //        'value' => 55,
     //        'product_option_id' => 2,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 5,
     //        'name' => 'Finland 1',
     //        'order' => 25,
     //        'value' => 21,
     //        'product_option_id' => 2,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 6,
     //        'name' => 'Finland 1',
     //        'order' => 6,
     //        'value' => 543,
     //        'product_option_id' => 2,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);

     //    DB::table('product_option_selects')->insert([
     //        'id' => 7,
     //        'name' => 'Fancy youuu',
     //        'order' => 7,
     //        'value' => 18,
     //        'product_option_id' => 3,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 8,
     //        'name' => 'Multi Ye 2',
     //        'order' => 8,
     //        'value' => 21,
     //        'product_option_id' => 3,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 9,
     //        'name' => 'Multi Ye 3',
     //        'order' => 9,
     //        'value' => 53,
     //        'product_option_id' => 3,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);

     //    DB::table('product_option_selects')->insert([
     //        'id' => 10,
     //        'name' => 'FIRE',
     //        'order' => 10,
     //        'value' => 59,
     //        'product_option_id' => 17,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 11,
     //        'name' => 'WATER',
     //        'order' => 11,
     //        'value' => 120,
     //        'product_option_id' => 17,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 12,
     //        'name' => 'EARTH',
     //        'order' => 12,
     //        'value' => 18,
     //        'product_option_id' => 17,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);

     //    DB::table('product_option_selects')->insert([
     //        'id' => 13,
     //        'name' => 'RANK 1',
     //        'order' => 13,
     //        'value' => 128,
     //        'product_option_id' => 18,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 14,
     //        'name' => 'RANK 2',
     //        'order' => 14,
     //        'value' => 221,
     //        'product_option_id' => 18,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 15,
     //        'name' => 'RANK 3',
     //        'order' => 15,
     //        'value' => 543,
     //        'product_option_id' => 18,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);

     //    DB::table('product_option_selects')->insert([
     //        'id' => 16,
     //        'name' => 'HR ASSISTANT',
     //        'order' => 16,
     //        'value' => 999,
     //        'product_option_id' => 19,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 17,
     //        'name' => 'HR OFFICER',
     //        'order' => 17,
     //        'value' => 666,
     //        'product_option_id' => 19,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 18,
     //        'name' => 'ACCOUNTANT',
     //        'order' => 18,
     //        'value' => 696,
     //        'product_option_id' => 19,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);

     //    DB::table('product_option_selects')->insert([
     //        'id' => 19,
     //        'name' => 'ORANGE',
     //        'order' => 19,
     //        'value' => 18,
     //        'product_option_id' => 32,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 20,
     //        'name' => 'PINK',
     //        'order' => 20,
     //        'value' => 21,
     //        'product_option_id' => 32,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 21,
     //        'name' => 'PORPOL',
     //        'order' => 21,
     //        'value' => 53,
     //        'product_option_id' => 32,
     //        'option_select_id' => 0,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    /*
     //    sELECT SUB
     //     */
     //    DB::table('product_option_selects')->insert([
     //        'id' => 22,
     //        'name' => 'PONGKAN',
     //        'order' => 22,
     //        'value' => 198,
     //        'product_option_id' => 32,
     //        'option_select_id' => 19,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 23,
     //        'name' => 'KYETKYET',
     //        'order' => 23,
     //        'value' => 231,
     //        'product_option_id' => 32,
     //        'option_select_id' => 19,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     //    DB::table('product_option_selects')->insert([
     //        'id' => 24,
     //        'name' => 'BASIC',
     //        'order' => 24,
     //        'value' => 253,
     //        'product_option_id' => 32,
     //        'option_select_id' => 19,
            
     //        'linked_option_id' => 0,
     //        'price_structure' => 'free',
     //        'price_type' => 0,
     //        'has_quantity' => 0,
     //        'is_discountable' => 0,
     //        'is_default' => 0,
     //        'deleted_at' => null,
     //        'created_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //        'updated_at' => Carbon::now()->format('Y-m-d H:i:s'),
     //    ]);
     }
}
