version: '3'
services:
  webserver:
    image: nginx:latest
    container_name: wwp2_webserver
    restart: always
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./public:/var/www/public
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/selfsigned.crt:/etc/nginx/certs/selfsigned.crt:ro
      - ./docker/nginx/selfsigned.key:/etc/nginx/certs/selfsigned.key:ro
      - ./storage/logs/nginx:/var/log/nginx
    links:
      - app
      - database

  database:
    image: mysql:5.7
    container_name: wwp2_database
    volumes:
      - ./storage/mysql/data:/var/lib/mysql:rw
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wwp2


  app:
    container_name: wwp2_app
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile-php-dev
    tty: true
    volumes:
      - .:/var/www
    entrypoint:
      - ./docker/php/entrypoint.sh
    links:
      - database